squirrel-server:
  environment:
    RACK_ENV: production
    RELEASES_FILE: https://s3-eu-west-1.amazonaws.com/electron-releases/releases.json
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: registry.magic-technik.de/ptv/squirrel-server:qa
  stdin_open: true
lb:
  ports:
  - 90:3000
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: rancher/load-balancer-service
  links:
  - squirrel-server:squirrel-server
  stdin_open: true
